name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-Docker-Image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag web:${{ github.sha }}
    - name: Trivy scan of Docker iamge
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: web:${{ github.sha }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
  
  Deploy-Docker-Image:
    runs-on: ubuntu:latest
    needs: build-Docker-Image
    steps:
      - name: Push to Docker hub
        run: echo "Pushing image to DockerHUB"

    

